-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 20:28:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `` ;

-- -----------------------------------------------------
-- Table ``.`akun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`akun` (
  `username_` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username_`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`booking_meja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`booking_meja` (
  `id_booking_meja` INT NOT NULL,
  `no_meja` VARCHAR(45) NULL,
  `tang` VARCHAR(45) NULL,
  `id_customer` VARCHAR(45) NULL,
  `jangka_waktu` VARCHAR(45) NULL,
  `jumlah_` VARCHAR(45) NULL,
  PRIMARY KEY (`id_booking_meja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`customer` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`pemesanan_cofeeshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`pemesanan_cofeeshop` (
  `id_pemesanan` INT NOT NULL,
  `id_customer` VARCHAR(45) NOT NULL,
  `jumlah_produk` VARCHAR(45) NOT NULL,
  `total_harga` VARCHAR(45) NOT NULL,
  `id_cofeeshop` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pemesanan`, `id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`cofeeshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`cofeeshop` (
  `id_cofeeshop` INT NOT NULL,
  `nama_menu` VARCHAR(45) NOT NULL,
  `harga` VARCHAR(45) NOT NULL,
  `diskon` VARCHAR(45) NOT NULL,
  `kategori` VARCHAR(45) NOT NULL,
  `gambar_menu` VARCHAR(45) NOT NULL,
  `pemesanan_id_pemesanan` INT NOT NULL,
  `pemesanan_id_customer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cofeeshop`, `pemesanan_id_pemesanan`, `pemesanan_id_customer`),
  INDEX `fk_cofeeshop_pemesanan1_idx` (`pemesanan_id_pemesanan` ASC, `pemesanan_id_customer` ASC),
  CONSTRAINT `fk_cofeeshop_pemesanan1`
    FOREIGN KEY (`pemesanan_id_pemesanan` , `pemesanan_id_customer`)
    REFERENCES ``.`pemesanan_cofeeshop` (`id_pemesanan` , `id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`homestay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`homestay` (
  `id_homestay` INT NOT NULL,
  `jenis_kamar` VARCHAR(45) NOT NULL,
  `fasilitas_kamar` VARCHAR(45) NOT NULL,
  `harga_kamar` VARCHAR(45) NOT NULL,
  `gambar` VARCHAR(45) NOT NULL,
  `id_pemesanan` INT NULL,
  `no_kamar` VARCHAR(45) NULL,
  `customer_id_customer` INT NOT NULL,
  `customer_akun_username_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_homestay`, `customer_id_customer`, `customer_akun_username_`),
  INDEX `fk_homestay_customer1_idx` (`customer_id_customer` ASC, `customer_akun_username_` ASC),
  CONSTRAINT `fk_homestay_customer1`
    FOREIGN KEY (`customer_id_customer` , `customer_akun_username_`)
    REFERENCES ``.`customer` (`id_customer` , `akun_username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`coursecofee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`coursecofee` (
  `id_coursecofee` INT NOT NULL,
  `pendaftaran` VARCHAR(100) NOT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `alamat` VARCHAR(45) NOT NULL,
  `no_telepon` INT NOT NULL,
  `profesi` VARCHAR(45) NOT NULL,
  `gambar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_coursecofee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`owner` (
  `id_owner` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `alamat` VARCHAR(45) NULL,
  `nomor_telepon` VARCHAR(45) NULL,
  `username_` VARCHAR(45) NULL,
  `password_` VARCHAR(45) NULL,
  `akun_username_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_owner`, `akun_username_`),
  INDEX `fk_owner_akun1_idx` (`akun_username_` ASC),
  CONSTRAINT `fk_owner_akun1`
    FOREIGN KEY (`akun_username_`)
    REFERENCES ``.`akun` (`username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`kritik_saran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`kritik_saran` (
  `id_aduan` INT NOT NULL,
  `nama_user` VARCHAR(45) NOT NULL,
  `subjek` VARCHAR(45) NOT NULL,
  `isi` TEXT NOT NULL,
  `tanggapan` TEXT NOT NULL,
  `customer_id_customer` INT NOT NULL,
  `customer_akun_username_` VARCHAR(45) NOT NULL,
  `owner_id_owner` INT NOT NULL,
  `owner_akun_username_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aduan`, `customer_id_customer`, `customer_akun_username_`, `owner_id_owner`, `owner_akun_username_`),
  INDEX `fk_kritik_saran_customer1_idx` (`customer_id_customer` ASC, `customer_akun_username_` ASC),
  INDEX `fk_kritik_saran_owner1_idx` (`owner_id_owner` ASC, `owner_akun_username_` ASC),
  CONSTRAINT `fk_kritik_saran_customer1`
    FOREIGN KEY (`customer_id_customer` , `customer_akun_username_`)
    REFERENCES ``.`customer` (`id_customer` , `akun_username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kritik_saran_owner1`
    FOREIGN KEY (`owner_id_owner` , `owner_akun_username_`)
    REFERENCES ``.`owner` (`id_owner` , `akun_username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`karyawan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`karyawan` (
  `id_karyawan` INT NOT NULL,
  `nama_karyawan` VARCHAR(45) NOT NULL,
  `alamat_karyawan` VARCHAR(45) NOT NULL,
  `no_telepon` INT NOT NULL,
  `posisi` VARCHAR(45) NOT NULL,
  `owner_id_owner` INT NOT NULL,
  `owner_akun_username_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_karyawan`, `owner_id_owner`, `owner_akun_username_`),
  INDEX `fk_karyawan_owner1_idx` (`owner_id_owner` ASC, `owner_akun_username_` ASC),
  CONSTRAINT `fk_karyawan_owner1`
    FOREIGN KEY (`owner_id_owner` , `owner_akun_username_`)
    REFERENCES ``.`owner` (`id_owner` , `akun_username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`Informasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`Informasi` (
  `id_informasi` INT NOT NULL,
  `subjek` VARCHAR(45) NOT NULL,
  `isi` TEXT NULL,
  `owner_id_owner` INT NOT NULL,
  `owner_akun_username_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_informasi`, `owner_id_owner`, `owner_akun_username_`),
  INDEX `fk_Informasi_owner1_idx` (`owner_id_owner` ASC, `owner_akun_username_` ASC),
  CONSTRAINT `fk_Informasi_owner1`
    FOREIGN KEY (`owner_id_owner` , `owner_akun_username_`)
    REFERENCES ``.`owner` (`id_owner` , `akun_username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`laundry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`laundry` (
  `id _laundry` INT NOT NULL,
  `total_baju` VARCHAR(50) NULL,
  `berat` VARCHAR(45) NULL,
  `harga` VARCHAR(45) NULL,
  `no_kamar` INT NOT NULL,
  `homestay_id_homestay` INT NOT NULL,
  `homestay_customer_id_customer` INT NOT NULL,
  `homestay_customer_akun_username_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id _laundry`, `no_kamar`, `homestay_id_homestay`, `homestay_customer_id_customer`, `homestay_customer_akun_username_`),
  INDEX `fk_laundry_homestay1_idx` (`homestay_id_homestay` ASC, `homestay_customer_id_customer` ASC, `homestay_customer_akun_username_` ASC),
  CONSTRAINT `fk_laundry_homestay1`
    FOREIGN KEY (`homestay_id_homestay` , `homestay_customer_id_customer` , `homestay_customer_akun_username_`)
    REFERENCES ``.`homestay` (`id_homestay` , `customer_id_customer` , `customer_akun_username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`registrasi_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`registrasi_course` (
  `id_registrasi_course` INT NOT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `alamat` VARCHAR(45) NOT NULL,
  `kelas` VARCHAR(45) NOT NULL,
  `no_telp` INT NOT NULL,
  PRIMARY KEY (`id_registrasi_course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`transaksi` (
  `id_transaksi` INT NOT NULL,
  `id_user` VARCHAR(45) NULL,
  `alamat_tujuan` VARCHAR(45) NULL,
  `identitas_penerima` VARCHAR(45) NULL,
  `nomor_telepon` VARCHAR(45) NULL,
  `total_pembayaran` VARCHAR(45) NULL,
  `tanggal_transaksi` DATE NULL,
  `bukti` VARCHAR(45) NULL,
  PRIMARY KEY (`id_transaksi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`admin` (
  `id_admin` INT NOT NULL,
  `username_` VARCHAR(45) NOT NULL,
  `nama_lengkap` VARCHAR(45) NOT NULL,
  `not_telp` INT NOT NULL,
  `password_` VARCHAR(45) NULL,
  `akun_username_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_admin`, `akun_username_`),
  INDEX `fk_admin_akun1_idx` (`akun_username_` ASC),
  CONSTRAINT `fk_admin_akun1`
    FOREIGN KEY (`akun_username_`)
    REFERENCES ``.`akun` (`username_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`customer` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`status_pemesanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`status_pemesanan` (
  `id_status_transaksi` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `keterangan` VARCHAR(45) NULL,
  `id_pemesanan` VARCHAR(45) NULL,
  `pemesanan_id_pemesanan` INT NOT NULL,
  `pemesanan_id_customer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status_transaksi`, `pemesanan_id_pemesanan`, `pemesanan_id_customer`),
  INDEX `fk_status_pemesanan_pemesanan1_idx` (`pemesanan_id_pemesanan` ASC, `pemesanan_id_customer` ASC),
  CONSTRAINT `fk_status_pemesanan_pemesanan1`
    FOREIGN KEY (`pemesanan_id_pemesanan` , `pemesanan_id_customer`)
    REFERENCES ``.`pemesanan_cofeeshop` (`id_pemesanan` , `id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``.`customer_has_cofeeshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ``.`customer_has_cofeeshop` (
  `customer_id_customer` INT NOT NULL,
  `customer_akun_username_` VARCHAR(45) NOT NULL,
  `customer_booking_meja_id_booking_meja` INT NOT NULL,
  `cofeeshop_id_cofeeshop` INT NOT NULL,
  `cofeeshop_pemesanan_id_pemesanan` INT NOT NULL,
  `cofeeshop_pemesanan_id_customer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id_customer`, `customer_akun_username_`, `customer_booking_meja_id_booking_meja`, `cofeeshop_id_cofeeshop`, `cofeeshop_pemesanan_id_pemesanan`, `cofeeshop_pemesanan_id_customer`),
  INDEX `fk_customer_has_cofeeshop_cofeeshop1_idx` (`cofeeshop_id_cofeeshop` ASC, `cofeeshop_pemesanan_id_pemesanan` ASC, `cofeeshop_pemesanan_id_customer` ASC),
  INDEX `fk_customer_has_cofeeshop_customer1_idx` (`customer_id_customer` ASC, `customer_akun_username_` ASC, `customer_booking_meja_id_booking_meja` ASC),
  CONSTRAINT `fk_customer_has_cofeeshop_customer1`
    FOREIGN KEY (`customer_id_customer` , `customer_akun_username_` , `customer_booking_meja_id_booking_meja`)
    REFERENCES ``.`customer` (`id_customer` , `akun_username_` , `booking_meja_id_booking_meja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_cofeeshop_cofeeshop1`
    FOREIGN KEY (`cofeeshop_id_cofeeshop` , `cofeeshop_pemesanan_id_pemesanan` , `cofeeshop_pemesanan_id_customer`)
    REFERENCES ``.`cofeeshop` (`id_cofeeshop` , `pemesanan_id_pemesanan` , `pemesanan_id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
